"""Extra visualization + diagnostics for rho_curve finite-size scaling.

Why this exists
- `analysis.rho_curve_scaling` already writes summary/fit and a few basic plots.
- For interpreting non-monotone k50(N) shapes and verifying data quality, we want
  additional figures (overlay curves, zoom-in crossings, residuals, heatmaps,
  and (k-k_inf)*N^beta style collapse attempts) plus a single per-N diagnostics CSV.

Design constraints
- Lives in `analysis/` and does NOT import `simulation/`.
- Stdlib-only for data plumbing; plotting uses optional `matplotlib`.
- Inputs are the same sweep CSVs used by scaling/report (ideally extracted from
  a compose script generated by `analysis.compose_rho_curve_commands`).

Typical usage (iter8 example)

./venv/bin/python -m analysis.rho_curve_viz \
  --prefix rho_curve_merged_with_lowband_clean_plus_prov2_S120_iter8_20260310_204815 \
  --summary outputs/analysis/rho_curve/<prefix>_summary.csv \
  --fit-json outputs/analysis/rho_curve/<prefix>_k50_fit.json \
  --compose outputs/_compose_cmds_<prefix>.sh \
  --outdir outputs/analysis/rho_curve \
  --eps 0.02 \
  --betas 0.5,0.8,1.0,1.5

Outputs
- PNGs under <outdir>/figs/<prefix>_*.png
- Diagnostics CSV: <outdir>/<prefix>_diagnostics.csv
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


@dataclass(frozen=True)
class SummaryRow:
	players: int
	k50: Optional[float]
	k50_bayes_mean: Optional[float]
	k50_bayes_ci_low: Optional[float]
	k50_bayes_ci_high: Optional[float]
	k_min: Optional[float]
	k_max: Optional[float]
	corr: Optional[float]
	rho_m1_50: Optional[float]
	k50_censored_low: bool


@dataclass(frozen=True)
class SweepStats:
	players: int
	score: float
	monov: int
	cross: int
	signchg: int
	points: int


def _try_float(v: object) -> Optional[float]:
	try:
		if v is None:
			return None
		s = str(v).strip()
		if s == "":
			return None
		return float(s)
	except Exception:
		return None


def _try_int(v: object) -> Optional[int]:
	try:
		if v is None:
			return None
		s = str(v).strip()
		if s == "":
			return None
		return int(float(s))
	except Exception:
		return None


def _read_summary(path: Path) -> List[SummaryRow]:
	rows: List[SummaryRow] = []
	with path.open("r", newline="") as f:
		r = csv.DictReader(f)
		for row in r:
			players = _try_int(row.get("players"))
			if players is None:
				continue
			rows.append(
				SummaryRow(
					players=int(players),
					k50=_try_float(row.get("k50")),
					k50_bayes_mean=_try_float(row.get("k50_bayes_mean")),
					k50_bayes_ci_low=_try_float(row.get("k50_bayes_ci_low")),
					k50_bayes_ci_high=_try_float(row.get("k50_bayes_ci_high")),
					k_min=_try_float(row.get("k_min")),
					k_max=_try_float(row.get("k_max")),
					corr=_try_float(row.get("corr_rho_minus_1_p_level_3")),
					rho_m1_50=_try_float(row.get("rho_minus_1_50")) or _try_float(row.get("rho_m1_50")),
					k50_censored_low=str(row.get("k50_censored_low") or "").strip().lower() in ("1", "true", "yes"),
				)
			)
	rows.sort(key=lambda x: x.players)
	return rows


def _extract_in_paths_from_compose(compose_sh: Path) -> List[Path]:
	text = compose_sh.read_text(encoding="utf-8", errors="replace")
	paths = re.findall(r"--in '([^']+)'", text)
	out: List[Path] = []
	seen: set[str] = set()
	for p in paths:
		pp = str(p).strip()
		if not pp:
			continue
		if pp in seen:
			continue
		seen.add(pp)
		out.append(Path(pp))
	return out


def _read_sweeps(paths: Sequence[Path]) -> Dict[int, List[Tuple[float, float]]]:
	by: Dict[int, List[Tuple[float, float]]] = {}
	for path in paths:
		if not path.exists():
			continue
		with path.open("r", newline="") as f:
			r = csv.DictReader(f)
			for row in r:
				players = _try_int(row.get("players"))
				k = _try_float(row.get("selection_strength"))
				p3 = _try_float(row.get("p_level_3"))
				if players is None or k is None or p3 is None:
					continue
				by.setdefault(int(players), []).append((float(k), float(p3)))
	# sort & de-dup by k (keep last)
	for n, pts in list(by.items()):
		pts.sort(key=lambda kv: kv[0])
		uniq: Dict[float, float] = {}
		for k, p3 in pts:
			uniq[float(k)] = float(p3)
		by[n] = sorted(uniq.items(), key=lambda kv: kv[0])
	return by


def _sweep_stats(by: Dict[int, List[Tuple[float, float]]], *, target: float, eps: float) -> Dict[int, SweepStats]:
	out: Dict[int, SweepStats] = {}
	for n, pts in by.items():
		y = [p[1] for p in pts]
		if len(y) < 5:
			continue

		monov = 0
		dys: List[float] = []
		for i in range(len(y) - 1):
			dy = float(y[i + 1]) - float(y[i])
			dys.append(dy)
			if dy < -float(eps):
				monov += 1

		signs: List[int] = []
		for dy in dys:
			if abs(float(dy)) <= float(eps):
				continue
			signs.append(1 if dy > 0.0 else -1)
		sc = 0
		for i in range(len(signs) - 1):
			if signs[i] != signs[i + 1]:
				sc += 1

		cross = 0
		for i in range(len(y) - 1):
			a = float(y[i]) - float(target)
			b = float(y[i + 1]) - float(target)
			if a == 0.0:
				continue
			if (a < 0.0 and b > 0.0) or (a > 0.0 and b < 0.0):
				cross += 1

		score = (2.0 * float(monov)) + (1.0 * float(cross)) + (0.25 * float(sc))
		out[int(n)] = SweepStats(players=int(n), score=float(score), monov=int(monov), cross=int(cross), signchg=int(sc), points=int(len(y)))
	return out


def _summary_score(row: SummaryRow) -> float:
	# Mirror analysis.select_noisy_players summary heuristic (for documentation parity).
	s = 0.0
	if row.corr is None:
		s += 1.0
	else:
		s += max(0.0, 1.0 - float(row.corr))
	if row.k50 is None:
		s += 1.0
	if row.k50_censored_low:
		s += 1.0
	if row.rho_m1_50 is not None:
		s += 0.25 * (1.0 / (1e-6 + abs(float(row.rho_m1_50))))
	return float(s)


def _ensure_matplotlib():
	try:
		import matplotlib  # noqa: F401
	except ModuleNotFoundError as e:
		raise SystemExit(
			"matplotlib 未安裝：此工具需要繪圖。\n"
			"請執行：./venv/bin/python -m pip install matplotlib\n"
			"或在 requirements.txt 取消註解 matplotlib（optional）。"
		) from e


def _plot_overlay_p3_vs_k(by: Dict[int, List[Tuple[float, float]]], *, outpath: Path, title: str) -> None:
	_ensure_matplotlib()
	import matplotlib.pyplot as plt

	plt.figure(figsize=(7, 4.2))
	for n in sorted(by.keys()):
		pts = by[n]
		x = [p[0] for p in pts]
		y = [p[1] for p in pts]
		plt.plot(x, y, marker="o", markersize=2.5, linewidth=1, label=f"N={n}")
	plt.axhline(0.5, color="black", linewidth=1, alpha=0.4)
	plt.xlabel("k (selection_strength)")
	plt.ylabel("P(Level3)")
	plt.title(title)
	plt.grid(True, alpha=0.25)
	plt.legend(ncol=3, fontsize=8)
	outpath.parent.mkdir(parents=True, exist_ok=True)
	plt.tight_layout()
	plt.savefig(outpath, dpi=170)
	plt.close()


def _plot_overlay_zoom(by: Dict[int, List[Tuple[float, float]]], *, centers: Dict[int, float], band: float, outpath: Path, title: str) -> None:
	_ensure_matplotlib()
	import matplotlib.pyplot as plt

	# choose a global window based on available centers
	vals = [centers[n] for n in centers if centers[n] is not None]
	if not vals:
		return
	k_lo = min(vals) - float(band)
	k_hi = max(vals) + float(band)

	plt.figure(figsize=(7, 4.2))
	for n in sorted(by.keys()):
		pts = [(k, p3) for (k, p3) in by[n] if k_lo <= k <= k_hi]
		if not pts:
			continue
		x = [p[0] for p in pts]
		y = [p[1] for p in pts]
		plt.plot(x, y, marker="o", markersize=3, linewidth=1, label=f"N={n}")
		if n in centers and centers[n] is not None:
			plt.axvline(float(centers[n]), linewidth=0.8, alpha=0.25)
	plt.axhline(0.5, color="black", linewidth=1, alpha=0.4)
	plt.xlim(k_lo, k_hi)
	plt.ylim(-0.02, 1.02)
	plt.xlabel("k (selection_strength)")
	plt.ylabel("P(Level3)")
	plt.title(title)
	plt.grid(True, alpha=0.25)
	plt.legend(ncol=3, fontsize=8)
	outpath.parent.mkdir(parents=True, exist_ok=True)
	plt.tight_layout()
	plt.savefig(outpath, dpi=170)
	plt.close()


def _plot_k50_transforms(summary: List[SummaryRow], *, fit: Optional[dict], outdir: Path, prefix: str) -> None:
	_ensure_matplotlib()
	import matplotlib.pyplot as plt

	pts = [(r.players, r.k50) for r in summary if r.players > 0 and r.k50 is not None and (not r.k50_censored_low)]
	if len(pts) < 2:
		return

	Ns = [p[0] for p in pts]
	Ks = [p[1] for p in pts]

	def _save(x, xlabel, name):
		plt.figure(figsize=(6.2, 4.0))
		plt.scatter(x, Ks, color="tab:blue")
		for n, xv, kv in zip(Ns, x, Ks):
			plt.annotate(f"N={n}", (xv, kv), textcoords="offset points", xytext=(4, 4), fontsize=8)
		plt.xlabel(xlabel)
		plt.ylabel("k50")
		plt.grid(True, alpha=0.25)
		plt.tight_layout()
		(outdir / f"{prefix}_{name}.png").parent.mkdir(parents=True, exist_ok=True)
		plt.savefig(outdir / f"{prefix}_{name}.png", dpi=170)
		plt.close()

	_save([1.0 / n for n in Ns], "1/N", "k50_vs_invN_alt")
	_save([1.0 / math.sqrt(n) for n in Ns], "1/sqrt(N)", "k50_vs_invSqrtN")
	_save([math.log(n) for n in Ns], "log(N)", "k50_vs_logN")

	# residual against fit model k_inf + c/N
	if fit and "k_inf" in fit and "c" in fit:
		k_inf = float(fit["k_inf"])
		c = float(fit["c"])
		res = [kv - (k_inf + c * (1.0 / n)) for n, kv in pts]
		plt.figure(figsize=(6.2, 3.8))
		plt.axhline(0.0, color="black", linewidth=1, alpha=0.4)
		plt.scatter(Ns, res, color="tab:purple")
		for n, rv in zip(Ns, res):
			plt.annotate(f"N={n}", (n, rv), textcoords="offset points", xytext=(4, 4), fontsize=8)
		plt.xlabel("N")
		plt.ylabel("k50 - (k_inf + c/N)")
		plt.title("Residual vs N (fit: k_inf + c/N)")
		plt.grid(True, alpha=0.25)
		plt.tight_layout()
		plt.savefig(outdir / f"{prefix}_k50_residual_vs_N.png", dpi=170)
		plt.close()

	# k50 with uncertainty band (if available)
	ci_pts = [
		(r.players, r.k50_bayes_mean, r.k50_bayes_ci_low, r.k50_bayes_ci_high)
		for r in summary
		if r.players > 0 and r.k50_bayes_mean is not None and r.k50_bayes_ci_low is not None and r.k50_bayes_ci_high is not None
	]
	if ci_pts:
		Ns2 = [p[0] for p in ci_pts]
		Ks2 = [float(p[1]) for p in ci_pts]
		err_lo = [float(p[1]) - float(p[2]) for p in ci_pts]
		err_hi = [float(p[3]) - float(p[1]) for p in ci_pts]
		plt.figure(figsize=(6.4, 4.0))
		plt.errorbar(Ns2, Ks2, yerr=[err_lo, err_hi], fmt="o", capsize=3, color="tab:blue")
		plt.xscale("log")
		plt.xlabel("N (log scale)")
		plt.ylabel("k50 (Bayes mean ± 95% CI)")
		plt.title("k50 vs N with Bayesian CI")
		plt.grid(True, alpha=0.25)
		plt.tight_layout()
		plt.savefig(outdir / f"{prefix}_k50_vs_N_with_ci.png", dpi=170)
		plt.close()


def _plot_collapse_k(by: Dict[int, List[Tuple[float, float]]], *, k_inf: float, beta: float, outpath: Path, title: str) -> None:
	_ensure_matplotlib()
	import matplotlib.pyplot as plt

	plt.figure(figsize=(6.6, 4.2))
	for n in sorted(by.keys()):
		pts = by[n]
		if not pts:
			continue
		x = [(k - float(k_inf)) * (float(n) ** float(beta)) for (k, _p3) in pts]
		y = [p3 for (_k, p3) in pts]
		plt.plot(x, y, marker="o", markersize=2.5, linewidth=1, label=f"N={n}")
	plt.axhline(0.5, color="black", linewidth=1, alpha=0.4)
	plt.axvline(0.0, color="black", linewidth=1, alpha=0.25)
	plt.xlabel(r"(k - k_inf) * N^beta")
	plt.ylabel("P(Level3)")
	plt.title(title)
	plt.grid(True, alpha=0.25)
	plt.legend(ncol=3, fontsize=8)
	outpath.parent.mkdir(parents=True, exist_ok=True)
	plt.tight_layout()
	plt.savefig(outpath, dpi=170)
	plt.close()


def _collapse_score(
	by: Dict[int, List[Tuple[float, float]]],
	*,
	k_inf: float,
	beta: float,
	bins: int = 35,
	p3_min: float = 0.0,
	p3_max: float = 1.0,
) -> float | None:
	"""Quantify collapse quality for x=(k-k_inf)N^beta.

	Heuristic: bin x over the common x-range and compute the mean cross-N
	variance of P(Level3) within bins. Lower is better.
	"""
	pts: list[tuple[float, float, int]] = []
	lo = float(p3_min)
	hi = float(p3_max)
	for n, seq in by.items():
		if not seq:
			continue
		for k, p3 in seq:
			pp = float(p3)
			if pp < lo or pp > hi:
				continue
			x = (float(k) - float(k_inf)) * (float(n) ** float(beta))
			if math.isfinite(x) and math.isfinite(pp):
				pts.append((float(x), pp, int(n)))
	if len(pts) < 20:
		return None

	xs = [p[0] for p in pts]
	x_lo = min(xs)
	x_hi = max(xs)
	if not (math.isfinite(x_lo) and math.isfinite(x_hi)):
		return None
	if abs(x_hi - x_lo) <= 1e-12:
		return None

	# Build bins.
	b = max(8, int(bins))
	step = (x_hi - x_lo) / float(b)
	acc: list[dict[int, list[float]]] = [dict() for _ in range(b)]
	for x, y, n in pts:
		i = int((x - x_lo) / step)
		if i < 0:
			continue
		if i >= b:
			i = b - 1
		acc[i].setdefault(int(n), []).append(float(y))

	# For each bin, compute cross-N variance of bin means.
	vars_: list[float] = []
	for mp in acc:
		if len(mp) < 2:
			continue
		means = []
		for ys in mp.values():
			if not ys:
				continue
			means.append(sum(ys) / float(len(ys)))
		if len(means) < 2:
			continue
		m = sum(means) / float(len(means))
		v = sum((a - m) * (a - m) for a in means) / float(len(means) - 1)
		vars_.append(float(v))
	if len(vars_) < 3:
		return None
	return float(sum(vars_) / float(len(vars_)))


def _interp_k_at_p(seq: Sequence[Tuple[float, float]], y: float) -> float | None:
	if not seq:
		return None
	y = float(y)
	best = None
	best_span = None
	for (k0, p0), (k1, p1) in zip(seq, seq[1:]):
		p0 = float(p0)
		p1 = float(p1)
		if not (math.isfinite(p0) and math.isfinite(p1)):
			continue
		if (p0 - y) == 0.0:
			return float(k0)
		if (p1 - y) == 0.0:
			return float(k1)
		if (p0 - y) * (p1 - y) > 0.0:
			continue
		den = (p1 - p0)
		if abs(den) <= 1e-15:
			continue
		t = (y - p0) / den
		if not math.isfinite(t):
			continue
		kk = float(k0) + float(t) * (float(k1) - float(k0))
		span = abs(p0 - y) + abs(p1 - y)
		if best is None or float(span) < float(best_span):
			best = float(kk)
			best_span = float(span)
	return best


def _collapse_score_ygrid(
	by: Dict[int, List[Tuple[float, float]]],
	*,
	k_inf: float,
	beta: float,
	y_grid: Sequence[float],
	p3_min: float = 0.0,
	p3_max: float = 1.0,
	min_ns_per_y: int = 2,
) -> float | None:
	"""Robust collapse score using interpolation in y=P(Level3).

	For each y in y_grid, interpolate k_N(y) along each N curve and compare
	x_N(y)=(k_N(y)-k_inf)N^beta across N. Score is mean cross-N variance.
	"""
	lo = float(p3_min)
	hi = float(p3_max)
	grid = [float(y) for y in y_grid if lo <= float(y) <= hi and math.isfinite(float(y))]
	if len(grid) < 3:
		return None

	filtered: Dict[int, List[Tuple[float, float]]] = {}
	for n, seq in by.items():
		if not seq:
			continue
		pts = [(float(k), float(p)) for (k, p) in seq if math.isfinite(float(k)) and math.isfinite(float(p))]
		if not pts:
			continue
		pts.sort(key=lambda kv: kv[0])
		pts2 = [(k, p) for (k, p) in pts if (p >= lo - 1e-12 and p <= hi + 1e-12)]
		if len(pts2) >= 2:
			filtered[int(n)] = pts2
	if len(filtered) < 2:
		return None

	vars_: list[float] = []
	for y in grid:
		xs: list[float] = []
		for n, seq in filtered.items():
			kk = _interp_k_at_p(seq, y)
			if kk is None:
				continue
			x = (float(kk) - float(k_inf)) * (float(n) ** float(beta))
			if math.isfinite(x):
				xs.append(float(x))
		if len(xs) < int(min_ns_per_y):
			continue
		m = sum(xs) / float(len(xs))
		v = sum((a - m) * (a - m) for a in xs) / float(len(xs) - 1) if len(xs) > 1 else 0.0
		if math.isfinite(v):
			vars_.append(float(v))
	if len(vars_) < 3:
		return None
	return float(sum(vars_) / float(len(vars_)))


def _interp_y_at_x(seq_xy: Sequence[Tuple[float, float]], x: float) -> float | None:
	if not seq_xy:
		return None
	x = float(x)
	x0 = float(seq_xy[0][0])
	x1 = float(seq_xy[-1][0])
	if x < min(x0, x1) - 1e-12 or x > max(x0, x1) + 1e-12:
		return None
	for (xa, ya), (xb, yb) in zip(seq_xy, seq_xy[1:]):
		xa = float(xa)
		xb = float(xb)
		if (xa - x) == 0.0:
			return float(ya)
		if (xb - x) == 0.0:
			return float(yb)
		if (xa - x) * (xb - x) > 0.0:
			continue
		den = (xb - xa)
		if abs(den) <= 1e-15:
			continue
		t = (x - xa) / den
		if not math.isfinite(t):
			continue
		yy = float(ya) + float(t) * (float(yb) - float(ya))
		return float(yy)
	return None


def _collapse_score_xgrid(
	by: Dict[int, List[Tuple[float, float]]],
	*,
	k_inf: float,
	beta: float,
	x_grid_n: int = 41,
	p3_min: float = 0.0,
	p3_max: float = 1.0,
	min_ns_per_x: int = 2,
) -> float | None:
	lo = float(p3_min)
	hi = float(p3_max)
	span = float(hi - lo)
	win_lo = float(lo + 0.10 * span)
	win_hi = float(hi - 0.10 * span)
	if not (win_hi > win_lo + 1e-12):
		win_lo = lo
		win_hi = hi
	seqs: Dict[int, List[Tuple[float, float]]] = {}
	x_at_lo: list[float] = []
	x_at_hi: list[float] = []
	for n, seq in by.items():
		if not seq:
			continue
		kp = [(float(k), float(p)) for (k, p) in seq if math.isfinite(float(k)) and math.isfinite(float(p))]
		if len(kp) < 2:
			continue
		kp.sort(key=lambda kv: kv[0])
		kp2 = [(k, p) for (k, p) in kp if (p >= lo - 1e-12 and p <= hi + 1e-12)]
		if len(kp2) >= 2:
			k_lo = _interp_k_at_p(kp2, win_lo)
			k_hi = _interp_k_at_p(kp2, win_hi)
			if k_lo is not None and k_hi is not None:
				x_at_lo.append((float(k_lo) - float(k_inf)) * (float(n) ** float(beta)))
				x_at_hi.append((float(k_hi) - float(k_inf)) * (float(n) ** float(beta)))
		pts = []
		for k, p in seq:
			pp = float(p)
			if not (pp >= lo and pp <= hi):
				continue
			x = (float(k) - float(k_inf)) * (float(n) ** float(beta))
			if math.isfinite(x) and math.isfinite(pp):
				pts.append((float(x), float(pp)))
		if len(pts) < 2:
			continue
		pts.sort(key=lambda kv: kv[0])
		uniq: Dict[float, float] = {}
		for x, y in pts:
			uniq[float(x)] = float(y)
		pts2 = sorted(uniq.items(), key=lambda kv: kv[0])
		if len(pts2) < 2:
			continue
		seqs[int(n)] = [(float(x), float(y)) for (x, y) in pts2]
	if len(seqs) < 2:
		return None
	if len(x_at_lo) < 3 or len(x_at_hi) < 3:
		return None
	x_at_lo.sort()
	x_at_hi.sort()
	def _pct(xs: list[float], q: float) -> float:
		q = max(0.0, min(1.0, float(q)))
		idx = int(round(q * float(len(xs) - 1)))
		idx = max(0, min(len(xs) - 1, idx))
		return float(xs[idx])
	q_pairs = [(0.80, 0.20), (0.70, 0.30), (0.65, 0.35), (0.60, 0.40), (0.55, 0.45), (0.50, 0.50)]
	x_lo = None
	x_hi = None
	for qlo, qhi in q_pairs:
		lo_q = _pct(x_at_lo, qlo)
		hi_q = _pct(x_at_hi, qhi)
		if math.isfinite(lo_q) and math.isfinite(hi_q) and hi_q > lo_q + 1e-12:
			x_lo = float(lo_q)
			x_hi = float(hi_q)
			break
	if x_lo is None or x_hi is None:
		return None
	if not (math.isfinite(x_lo) and math.isfinite(x_hi)):
		return None
	if x_hi <= x_lo + 1e-12:
		return None

	nx = max(11, int(x_grid_n))
	step = (x_hi - x_lo) / float(nx - 1)
	vars_: list[float] = []
	for i in range(nx):
		x = x_lo + float(i) * step
		ys: list[float] = []
		for _n, sxy in seqs.items():
			y = _interp_y_at_x(sxy, x)
			if y is None:
				continue
			if math.isfinite(float(y)):
				ys.append(float(y))
		if len(ys) < int(min_ns_per_x):
			continue
		m = sum(ys) / float(len(ys))
		v = sum((a - m) * (a - m) for a in ys) / float(len(ys) - 1) if len(ys) > 1 else 0.0
		if math.isfinite(v):
			vars_.append(float(v))
	if len(vars_) < max(3, int(0.3 * float(nx))):
		return None
	return float(sum(vars_) / float(len(vars_)))


def _parse_grid_spec(spec: str) -> list[float]:
	s = str(spec).strip()
	if ":" in s:
		parts = [p.strip() for p in s.split(":")]
		if len(parts) != 3:
			raise ValueError("grid must be lo:hi:step")
		lo = float(parts[0])
		hi = float(parts[1])
		st = float(parts[2])
		if st <= 0:
			raise ValueError("step must be >0")
		out: list[float] = []
		x = lo
		k = 0
		while x <= hi + 1e-12 and k < 100000:
			out.append(float(x))
			k += 1
			x = lo + k * st
		return out
	# comma list
	out: list[float] = []
	for part in s.split(","):
		part = part.strip()
		if not part:
			continue
		out.append(float(part))
	return out


def _plot_heatmap(by: Dict[int, List[Tuple[float, float]]], *, outpath: Path, title: str) -> None:
	_ensure_matplotlib()
	import matplotlib.pyplot as plt
	import numpy as np

	Ns = sorted(by.keys())
	if not Ns:
		return
	# union grid of k
	k_vals = sorted({float(k) for pts in by.values() for (k, _p3) in pts})
	if len(k_vals) < 2:
		return
	Z = np.full((len(Ns), len(k_vals)), np.nan, dtype=float)
	for i, n in enumerate(Ns):
		mp = {float(k): float(p3) for (k, p3) in by[n]}
		for j, k in enumerate(k_vals):
			if k in mp:
				Z[i, j] = mp[k]

	plt.figure(figsize=(8.0, 3.8))
	im = plt.imshow(Z, aspect="auto", origin="lower", interpolation="nearest")
	plt.colorbar(im, label="P(Level3)")
	plt.yticks(range(len(Ns)), [str(n) for n in Ns])
	# x ticks: sparse
	x_ticks = list(range(0, len(k_vals), max(1, len(k_vals) // 10)))
	plt.xticks(x_ticks, [f"{k_vals[i]:.3g}" for i in x_ticks], rotation=45, ha="right")
	plt.xlabel("k (selection_strength)")
	plt.ylabel("players (N)")
	plt.title(title)
	plt.tight_layout()
	outpath.parent.mkdir(parents=True, exist_ok=True)
	plt.savefig(outpath, dpi=170)
	plt.close()


def _write_diagnostics_csv(
	*,
	outpath: Path,
	summary: List[SummaryRow],
	sweep_stats: Dict[int, SweepStats],
	k50_fit: Optional[dict],
	eps: float,
	target: float,
) -> None:
	outpath.parent.mkdir(parents=True, exist_ok=True)
	with outpath.open("w", newline="") as f:
		w = csv.DictWriter(
			f,
			fieldnames=[
				"players",
				"k50",
				"k50_bayes_mean",
				"k50_bayes_ci_low",
				"k50_bayes_ci_high",
				"k_min",
				"k_max",
				"corr_rho_minus_1_p_level_3",
				"rho_minus_1_50",
				"k50_censored_low",
				"summary_score",
				"sweeps_score",
				"monov",
				"cross",
				"signchg",
				"points",
				"eps",
				"target",
				"k_inf",
				"c",
				"r2",
			],
		)
		w.writeheader()
		for r in sorted(summary, key=lambda x: x.players):
			st = sweep_stats.get(r.players)
			fit = k50_fit or {}
			w.writerow(
				{
					"players": r.players,
					"k50": r.k50,
					"k50_bayes_mean": r.k50_bayes_mean,
					"k50_bayes_ci_low": r.k50_bayes_ci_low,
					"k50_bayes_ci_high": r.k50_bayes_ci_high,
					"k_min": r.k_min,
					"k_max": r.k_max,
					"corr_rho_minus_1_p_level_3": r.corr,
					"rho_minus_1_50": r.rho_m1_50,
					"k50_censored_low": int(bool(r.k50_censored_low)),
					"summary_score": _summary_score(r),
					"sweeps_score": (st.score if st else None),
					"monov": (st.monov if st else None),
					"cross": (st.cross if st else None),
					"signchg": (st.signchg if st else None),
					"points": (st.points if st else None),
					"eps": float(eps),
					"target": float(target),
					"k_inf": fit.get("k_inf"),
					"c": fit.get("c"),
					"r2": fit.get("r2"),
				}
			)


def main(argv: Optional[Sequence[str]] = None) -> None:
	p = argparse.ArgumentParser(description="Extra rho_curve diagnostics plots + per-N metrics")
	p.add_argument("--prefix", required=True, help="Prefix used for naming outputs")
	p.add_argument("--summary", required=True, help="Path to *_summary.csv")
	p.add_argument("--fit-json", default=None, help="Path to *_k50_fit.json (optional)")
	p.add_argument("--compose", default=None, help="Compose .sh produced by analysis.compose_rho_curve_commands (optional)")
	p.add_argument("--in", dest="inputs", action="append", default=[], help="Sweep CSV path (repeatable); alternative to --compose")
	p.add_argument("--outdir", default="outputs/analysis/rho_curve", help="Output directory (default: outputs/analysis/rho_curve)")
	p.add_argument("--eps", type=float, default=0.02, help="Eps tolerance for monotonicity/sign checks (default: 0.02)")
	p.add_argument("--target", type=float, default=0.5, help="Crossing target for sweeps stats (default: 0.5)")
	p.add_argument("--betas", default="0.5,0.8,1.0,1.5", help="Comma-separated beta list for collapse (default: 0.5,0.8,1.0,1.5)")
	p.add_argument(
		"--k-inf",
		type=float,
		default=None,
		help="Optional override for k_inf used in collapse plots/scores (default: take from --fit-json).",
	)
	p.add_argument("--zoom-band", type=float, default=0.12, help="Global k window half-width for zoom plot (default: 0.12)")
	p.add_argument(
		"--collapse-pmin",
		type=float,
		default=0.1,
		help="Only use points with P(Level3) >= this for collapse scoring (default: 0.1)",
	)
	p.add_argument(
		"--collapse-pmax",
		type=float,
		default=0.9,
		help="Only use points with P(Level3) <= this for collapse scoring (default: 0.9)",
	)
	p.add_argument(
		"--collapse-score-method",
		choices=["xbins", "xgrid", "ygrid"],
		default="xbins",
		help="Collapse score method: xbins (legacy), xgrid (robust), or ygrid (experimental) (default: xbins)",
	)
	p.add_argument("--collapse-x-grid-n", type=int, default=41, help="For xgrid: number of x grid points (default: 41)")
	p.add_argument(
		"--collapse-y-grid",
		default=None,
		help="For ygrid method: y values as lo:hi:step or comma list (default: use collapse-pmin..collapse-pmax step 0.02)",
	)
	args = p.parse_args(list(argv) if argv is not None else None)

	prefix = str(args.prefix)
	outdir = Path(str(args.outdir))
	figdir = outdir / "figs"
	figdir.mkdir(parents=True, exist_ok=True)

	summary_path = Path(str(args.summary))
	summary = _read_summary(summary_path)
	centers = {r.players: float(r.k50) for r in summary if r.k50 is not None}

	fit: Optional[dict] = None
	if args.fit_json:
		fit_path = Path(str(args.fit_json))
		if fit_path.exists():
			fit = json.loads(fit_path.read_text(encoding="utf-8"))

	in_paths: List[Path] = []
	if args.compose:
		in_paths = _extract_in_paths_from_compose(Path(str(args.compose)))
	else:
		in_paths = [Path(x) for x in (args.inputs or [])]
	if not in_paths:
		raise SystemExit("需要提供 --compose 或至少一個 --in")

	by = _read_sweeps(in_paths)
	stats = _sweep_stats(by, target=float(args.target), eps=float(args.eps))

	# figures
	_plot_overlay_p3_vs_k(by, outpath=figdir / f"{prefix}_pL3_vs_k_overlay.png", title="P(Level3) vs k (overlay; all N)")
	_plot_overlay_zoom(
		by,
		centers=centers,
		band=float(args.zoom_band),
		outpath=figdir / f"{prefix}_pL3_vs_k_overlay_zoom.png",
		title="P(Level3) vs k (zoom around crossings)",
	)

	_plot_heatmap(by, outpath=figdir / f"{prefix}_pL3_heatmap_k_by_N.png", title="Heatmap: P(Level3) over (N, k)")

	_plot_k50_transforms(summary, fit=fit, outdir=figdir, prefix=prefix)

	# collapse attempts
	betas = []
	for part in str(args.betas).split(","):
		part = part.strip()
		if not part:
			continue
		try:
			betas.append(float(part))
		except Exception:
			continue

	k_inf: float | None = None
	if args.k_inf is not None:
		k_inf = float(args.k_inf)
	elif fit and "k_inf" in fit and fit["k_inf"] is not None:
		k_inf = float(fit["k_inf"])
	if k_inf is not None and betas:
		scores: dict[str, float] = {}
		score_method = str(args.collapse_score_method)
		if score_method == "ygrid":
			if args.collapse_y_grid is None:
				y_grid = _parse_grid_spec(f"{float(args.collapse_pmin)}:{float(args.collapse_pmax)}:0.02")
				y_grid_spec = f"{float(args.collapse_pmin)}:{float(args.collapse_pmax)}:0.02"
			else:
				y_grid = _parse_grid_spec(str(args.collapse_y_grid))
				y_grid_spec = str(args.collapse_y_grid)
		else:
			y_grid = []
			y_grid_spec = None
		for b in betas:
			_plot_collapse_k(
				by,
				k_inf=float(k_inf),
				beta=float(b),
				outpath=figdir / f"{prefix}_collapse_k_kInf_{k_inf:.4f}_beta_{b:g}.png",
				title=f"Collapse attempt: (k-k_inf)N^beta (k_inf={k_inf:.4f}, beta={b:g})",
			)
			if score_method == "ygrid":
				s = _collapse_score_ygrid(
					by,
					k_inf=float(k_inf),
					beta=float(b),
					y_grid=y_grid,
					p3_min=float(args.collapse_pmin),
					p3_max=float(args.collapse_pmax),
				)
			elif score_method == "xgrid":
				s = _collapse_score_xgrid(
					by,
					k_inf=float(k_inf),
					beta=float(b),
					x_grid_n=int(args.collapse_x_grid_n),
					p3_min=float(args.collapse_pmin),
					p3_max=float(args.collapse_pmax),
				)
			else:
				s = _collapse_score(
					by,
					k_inf=float(k_inf),
					beta=float(b),
					p3_min=float(args.collapse_pmin),
					p3_max=float(args.collapse_pmax),
				)
			if s is not None:
				scores[f"{float(b):g}"] = float(s)
		if scores:
			best_beta = min(scores.items(), key=lambda kv: kv[1])[0]
			out_json = figdir / f"{prefix}_collapse_scores_kInf_{k_inf:.4f}.json"
			out_json.write_text(
				json.dumps(
					{
						"k_inf": float(k_inf),
						"scores": scores,
						"best_beta": best_beta,
						"score_method": score_method,
						"collapse_pmin": float(args.collapse_pmin),
						"collapse_pmax": float(args.collapse_pmax),
						"x_grid_n": int(args.collapse_x_grid_n),
						"y_grid_spec": y_grid_spec,
						"y_grid": y_grid if score_method == "ygrid" else None,
					},
					indent=2,
				),
				encoding="utf-8",
			)
			print(f"Collapse scores: wrote {out_json} (best_beta={best_beta})")

	# per-N diagnostics CSV
	_write_diagnostics_csv(
		outpath=outdir / f"{prefix}_diagnostics.csv",
		summary=summary,
		sweep_stats=stats,
		k50_fit=fit,
		eps=float(args.eps),
		target=float(args.target),
	)

	print(f"Wrote figures under: {figdir}")
	print(f"Wrote diagnostics: {outdir / f'{prefix}_diagnostics.csv'}")


if __name__ == "__main__":
	main()
